name = "cocoyoshizawa-bio"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[env.production]
vars = { ENVIRONMENT = "production" }

# Note: NEON_DATABASE_URL must be configured as an environment variable
# in Cloudflare Pages dashboard (Settings > Environment variables)
